name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Clona el repositori
        uses: actions/checkout@v4

      - name: 📦 Cache de npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: ⚙️ Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📥 Instal·la dependències
        run: npm ci

      - name: 🏗️ Compila el projecte
        run: npm run build
        env:
          PUBLIC_FORMSPREE_ID: ${{ secrets.PUBLIC_FORMSPREE_ID }}

      - name: 🔑 Configura SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 📂 Upload build al servidor via rsync
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p 65002" dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/u391072230/domains/3cat.elink.cat/public_html/
